development: &development
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: refinery_site_development

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: refinery_site_test

production: &production
  adapter: mysql2
  host: localhost
  database: your_production_database
  username: your_production_database_login
  password: your_production_database_password
